# _config.toml

# ------------------------------------------------------------  IO
[io]
    filename_input  = "params.csv"      # temporary csv file for setting HFSS params
    filename_output = "results.csv"     # csv file for storing results
    filename_temp   = "temp_hfss_export.csv" # temporary csv file for passing results

# ------------------------------------------------------------  Simulation/Hyperparams
[sim]
    n_simulation    = 70   # maximum number of smulations per each iteration
    n_repeats       = 5     # total nuber of iterations
    n_init          = 20
    kernel_type     = "RBF" # kernel name
    n_params        = 4
    length_scale    = 1.0
    noise_std       = 0.01
    noise_var       = 0.0001
    lower_bounds    = [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100]
    upper_bounds    = [0.215, 0.850, 0.215, 0.850, 0.215, 0.850, 0.215, 0.850]
    param_names     = ['s1x', 's1y', 's2x', 's2y', 's3x', 's3y', 's4x', 's4y']

# ------------------------------------------------------------  GP Hyperparams
[opt]
    kernel_type     = "RBF" # kernel name
    length_scale    = 1.0
    noise_std       = 0.01
    noise_var       = 0.0001

# ------------------------------------------------------------  HFSS simulation
[hfss]
    n_simulation    = 30  # maximum number of smulations per each iteration
    n_repeats       = 1   # total nuber of iterations
    n_init          = 10
    #n_params       = 8
    n_params        = 4
    #lower_bounds   = [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100]
    lower_bounds    = [0.100, 0.100, 0.100, 0.100]
    #upper_bounds   = [0.215, 0.850, 0.215, 0.850, 0.215, 0.850, 0.215, 0.850]
    upper_bounds    = [0.850, 0.850, 0.850, 0.850]
    #param_names    = ['s1x', 's1y', 's2x', 's2y', 's3x', 's3y', 's4x', 's4y']
    param_names     = ['s1y', 's2y', 's3y', 's4y']


# ------------------------------------------------------------  Synthetic Test Function
[test]
    n_simulation    = 130
    n_repeats       = 1     # total nuber of iterations
    n_init          = 30
    n_params        = 10
    lower_bounds    = [-32, -32, -32, -32, -32, -32, -32, -32, -32, -32]
    upper_bounds    = [32, 32, 32, 32, 32, 32, 32, 32, 32, 32]
    param_names     = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10',]
